# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UISettingsWindow(object):
    def __init__(self, game_ui):
        self.game_ui = game_ui

    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(320, 240)
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_apply_and_restart = QtWidgets.QPushButton(self.centralwidget)
        self.btn_apply_and_restart.setGeometry(QtCore.QRect(0, 180, 320, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_apply_and_restart.sizePolicy().hasHeightForWidth())
        self.btn_apply_and_restart.setSizePolicy(sizePolicy)
        self.btn_apply_and_restart.setObjectName("btn_apply_and_restart")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(0, 20, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 61, 16))
        self.label.setObjectName("label")
        SettingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

        self.btn_apply_and_restart.clicked.connect(
            lambda: self.game_ui.set_difficulty_and_restart_game(self.comboBox.currentText())
        )

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings"))
        self.btn_apply_and_restart.setText(_translate("SettingsWindow", "Применить и перезапустить"))
        self.comboBox.setItemText(0, _translate("SettingsWindow", "Легкий"))
        self.comboBox.setItemText(1, _translate("SettingsWindow", "Средний"))
        self.comboBox.setItemText(2, _translate("SettingsWindow", "Сложный"))
        self.label.setText(_translate("SettingsWindow", "Сложность"))
